#! /bin/sh
# chkconfig: 2345 55 25
# Description: Startup script for nginx webserver on Debian. Place in /etc/init.d and
# run 'update-rc.d -f nginx defaults', or use the appropriate command on your
# distro. For CentOS/Redhat run: 'chkconfig --add nginx'

### BEGIN INIT INFO
# Provides:          nginx
# Required-Start:    $all
# Required-Stop:     $all
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: starts the nginx web server
# Description:       starts nginx using start-stop-daemon
### END INIT INFO

prefix=/usr
exec_prefix=${prefix}

NGINX_BIN=${exec_prefix}/sbin/nginx
NGINX_CONF=/etc/nginx/nginx.conf
NGINX_PID=/var/run/nginx.pid

case "$1" in
    start)
        echo -n "Starting nginx... "

        if netstat -tnpl | grep -q nginx;then
            echo "nginx (pid `pidof nginx`) already running."
            exit 1
        fi

        $NGINX_BIN -c $NGINX_CONF

        if [ "$?" != 0 ] ; then
            echo " failed"
            exit 1
        else
            echo " done"
        fi
        ;;

    stop)
        echo -n "Stoping nginx... "

        if ! netstat -tnpl | grep -q nginx; then
            echo "nginx is not running."
            exit 1
        fi

        $NGINX_BIN -s stop

        if [ "$?" != 0 ] ; then
            echo " failed. Use force-quit"
            exit 1
        else
            echo " done"
        fi
        ;;

    status)
        if netstat -tnpl | grep -q nginx; then
            PID=`pidof nginx`
            echo "nginx (pid $PID) is running..."
        else
            echo "nginx is stopped"
            exit 0
        fi
        ;;

    force-quit)
        echo -n "Terminating nginx... "

        if ! netstat -tnpl | grep -q nginx; then
            echo "nginx is not running."
            exit 1
        fi

        kill `pidof nginx`

        if [ "$?" != 0 ] ; then
            echo " failed"
            exit 1
        else
            echo " done"
        fi
        ;;

    restart)
        $0 stop
        sleep 1
        $0 start
        ;;

    reload)
        echo -n "Reload service nginx... "

        if netstat -tnpl | grep -q nginx; then
            $NGINX_BIN -s reload
            echo " done"
        else
            echo "nginx is not running, can't reload."
            exit 1
        fi
        ;;

    configtest)
        echo -n "Test nginx configure files... "

        $NGINX_BIN -t
        ;;

    *)
        echo "Usage: $0 {start|stop|force-quit|restart|reload|status|configtest}"
        exit 1
        ;;

esac